### ISSUE TITLE
In ColdFusion 2018 'function' is a reserved word. 

### ISSUE THREAD

**Issue by wilgeno** [sebtools/DataMgr#2]
In ColdFusion 2018 'function' is a reserved word. 

I made a fix If I can get push permissions.

**Comment by ethicssystems** [comment]
Have you seen this error before? I only got it after upgrading to CF 2018...

Invalid construct: Either argument or name is missing.
--
When using named parameters to a function, each parameter must have a name.
The CFML compiler was processing:

- An expression beginning with getRecords, on line 3347, column 31.This message is usually caused by a problem in the expressions structure.
- A cfset tag beginning on line 3347, column 10.
- A cfset tag beginning on line 3347, column 10.

The error occurred in D:/wwwroot/CFCs/_DataMgr.cfc: line 3347
Called from D:/wwwroot/application.cfc: line 15
Called from D:/wwwroot/application.cfc: line 9
--
3345 : 	<cfargument name="data" type="struct" default="#StructNew()#" hint="A structure with the data for the desired record. Each key/value indicates a value for the field matching that key."> 3346 : 
3347 : 	<cfset var qRecords = getRecords(tablename=arguments.tablename,data=arguments.data,function="count",FunctionAlias="NumRecords")> 
3348 :  
3349 : 	<cfreturn Val(qRecords.NumRecords)>

**Comment by ethicssystems** [comment]
OK, ignore earlier entry. This seems to be solved by installing  CF 2018 Update 7.

**Comment by sebtools** [comment]
Glad it was solved by a version update!
